/**
 * Pull the plugin's GLSL out of source/shaders/ and write demo/shaders.js.
 *
 *     node demo/extract-shaders.mjs
 *
 * The rest of the fleet's demos carry their shaders as strings "copied
 * unedited from source/shaders/", and the honest thing to say about that is
 * that nothing checks it. A copy is a copy: the plugin's shader gets a fix, the
 * demo's does not, and the page quietly stops being a demo of the plugin.
 *
 * So this repo generates instead. `demo/shaders.js` is committed -- the demo is
 * hand-written ES modules served as they are, with no build step, and that must
 * stay true -- but it is generated, and `--check` fails if it has drifted from
 * the C++. Run that in verify.sh and the two cannot part company.
 *
 * The extraction is deliberately dumb: find `kName = R"( ... )"` and take what
 * is between the delimiters. It is not a C++ parser and must never become one,
 * for the same reason the kit's `port()` is not a GLSL parser -- the moment it
 * is clever enough to rewrite anything, the demo stops running the plugin's
 * shader.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const shaderDir = join(here, '..', 'source', 'shaders');

const FILES = ['Vertex.cpp', 'FieldGLSL.cpp', 'Beam.cpp', 'Phosphor.cpp', 'Bloom.cpp', 'Screen.cpp'];

/** Every `kSomething = R"( ... )"` in a file, by name. */
function extract(path) {
  const text = readFileSync(path, 'utf8');
  const found = {};
  // Non-greedy up to the first `)"`, which is safe because GLSL cannot contain
  // that sequence: `)` only ever closes a call or a parameter list, and the
  // character after it is never a double quote.
  const re = /(\bk[A-Za-z0-9_]+)\s*=\s*R"\(([\s\S]*?)\)";/g;
  let m;
  while ((m = re.exec(text)) !== null) found[m[1]] = m[2];
  return found;
}

const parts = {};
for (const file of FILES) Object.assign(parts, extract(join(shaderDir, file)));

const required = [
  'kVertex', 'kFieldUniforms', 'kFieldFunction', 'kBeamBody', 'kBeamMain',
  'kPhosphorFragment', 'kBloomFragment', 'kBlurFragment', 'kScreenFragment',
];
const missing = required.filter((k) => !(k in parts));
if (missing.length) {
  console.error(`extract-shaders: could not find ${missing.join(', ')} in source/shaders/`);
  process.exit(2);
}

// Assembled exactly as shaders::BeamFragmentSource() assembles it. If that
// function's order changes, this line has to change with it -- which is the one
// piece of duplication left, and it is three identifiers long.
const beam = `#version 410 core\n${parts.kFieldUniforms}${parts.kBeamBody}${parts.kFieldFunction}${parts.kBeamMain}`;

const escape = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

const out = `/**
 * GENERATED by demo/extract-shaders.mjs from source/shaders/. Do not edit.
 *
 * These are the plugin's own shaders, character for character. Re-run the
 * extractor after touching any of them; \`tools/verify.sh\` fails if this file
 * has drifted from the C++.
 */

export const VERTEX = ${escape(parts.kVertex)};
export const BEAM = ${escape(beam)};
export const PHOSPHOR = ${escape(parts.kPhosphorFragment)};
export const BLOOM = ${escape(parts.kBloomFragment)};
export const BLUR = ${escape(parts.kBlurFragment)};
export const SCREEN = ${escape(parts.kScreenFragment)};
`;

const target = join(here, 'shaders.js');

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    /* missing counts as drifted */
  }
  if (current !== out) {
    console.error('demo/shaders.js has drifted from source/shaders/. Run: node demo/extract-shaders.mjs');
    process.exit(1);
  }
  console.log('demo/shaders.js matches source/shaders/');
} else {
  writeFileSync(target, out);
  console.log(`wrote ${target} (${out.length} bytes)`);
}
