/**
 * GENERATED by demo/extract-shaders.mjs from source/shaders/. Do not edit.
 *
 * These are the plugin's own shaders, character for character. Re-run the
 * extractor after touching any of them; `tools/verify.sh` fails if this file
 * has drifted from the C++.
 */

export const VERTEX = `#version 410 core
layout( location = 0 ) in vec4 vPosition;
layout( location = 1 ) in vec2 vUV;

out vec2 uv;

void main()
{
	gl_Position = vPosition;
	uv = vUV;
}
`;
export const BEAM = `#version 410 core

//The magnets: xy is position in square tube units, z is signed strength.
uniform vec3 Pole0;
uniform vec3 Pole1;
uniform vec3 Pole2;
uniform vec3 Pole3;
uniform float PoleHeight;

uniform sampler2D InputTexture;
uniform vec2 MaxUV;
uniform vec2 InputSize;
uniform vec2 OutputSize;

//The two sensitivities. See Controls.h -- they are separate on purpose,
//because a real tube's two sensitivities are set by different hardware.
uniform float Deflection;
uniform float PurityGainX;
uniform float PurityGainY;

uniform float GunSeparation;
uniform float GunTriangular;//delta gun (1) or in-line gun (0)

uniform float StaticAmp;    //what the mask itself is holding
uniform float AcAmp;        //ambient interference plus whatever the coil is doing
uniform float Frequency;    //Hz
uniform float Time;         //seconds
uniform float ScanPeriod;   //seconds to paint one raster, top to bottom

uniform float Swell;        //HT sag pushes the picture outwards
uniform float Sag;          //...and dims it
uniform float Overscan;

in vec2 uv;

out vec4 fragColor;

//= mirrored: regauss::fieldAt() in Field.cpp. Checked by rgtest --field.
vec2 fieldAt( vec2 p )
{
	vec2 b = vec2( 0.0 );
	vec3 poles[ 4 ] = vec3[ 4 ]( Pole0, Pole1, Pole2, Pole3 );

	for( int i = 0; i < 4; ++i )
	{
		vec2 d = p - poles[ i ].xy;
		//The pole sits off the plane of the glass, so this is a real 3-D
		//distance and there is no singularity anywhere on the face. The
		//exponent is one rather than three halves -- this is the field
		//integrated along the beam's flight, not the field where it lands.
		//See Field.h.
		float r2 = dot( d, d ) + PoleHeight * PoleHeight;
		b += d * ( poles[ i ].z / r2 );
	}

	return b;
}

void main()
{
	float aspect = OutputSize.x / max( OutputSize.y, 1.0 );

	//Picture coordinates, -1..1 on both axes, and the same point in SQUARE
	//units. The field lives in square units so that a round magnet makes a
	//round stain on a 16:9 composition; the picture lives in picture units
	//because that is what the texture is indexed by.
	vec2 pic = uv * 2.0 - 1.0;
	vec2 sq  = vec2( pic.x * aspect, pic.y );

	//----------------------------------------------------------------------
	// How strong the field is, right here, right now.
	//
	// The scan-position term is the one worth understanding. The beam paints
	// the raster from the top down over one frame period, so the bottom of the
	// picture is drawn a whole frame LATER than the top -- and if the field is
	// alternating, it has moved on by then. That is the entire mechanism
	// behind the slow vertical roll of mains interference: at exactly the
	// field rate every line sees the same phase and the bend is stationary,
	// and a hertz or two either side it crawls up or down the screen. Take
	// this term out and the picture flickers in place instead, which is what
	// interference has never once looked like.
	//----------------------------------------------------------------------
	float ac  = sin( 6.2831853 * Frequency * ( Time + ( 1.0 - uv.y ) * ScanPeriod ) );
	float amp = StaticAmp + AcAmp * ac;

	//----------------------------------------------------------------------
	// Three guns, three paths, three fields.
	//
	// A delta gun has its three cathodes on a triangle and an in-line gun has
	// them in a row, which is not a detail: it decides whether the fringing
	// comes out as a vertical red/blue split or as a three-way spray. The
	// choice follows the mask, because the tube was built as one thing -- a
	// delta shadow mask is fed by a delta gun and a grille by an in-line gun.
	//----------------------------------------------------------------------
	vec2 gun[ 3 ];
	if( GunTriangular > 0.5 )
	{
		gun[ 0 ] = vec2( 0.0, 1.0 ) * GunSeparation;
		gun[ 1 ] = vec2( -0.866, -0.5 ) * GunSeparation;
		gun[ 2 ] = vec2( 0.866, -0.5 ) * GunSeparation;
	}
	else
	{
		gun[ 0 ] = vec2( -1.0, 0.0 ) * GunSeparation;
		gun[ 1 ] = vec2( 0.0, 0.0 );
		gun[ 2 ] = vec2( 1.0, 0.0 ) * GunSeparation;
	}

	vec2 halfTexel = 0.5 / max( InputSize, vec2( 1.0 ) );

	vec3 sampled = vec3( 0.0 );
	vec3 landing = vec3( 0.0 );//each gun's error, in phosphor widths
	float alpha  = 0.0;
	float inside = 0.0;

	for( int c = 0; c < 3; ++c )
	{
		//The field this gun's beam flies through, which is NOT the field at
		//the point it is aimed at. In picture units, undoing the aspect
		//stretch the field was evaluated in.
		vec2 b     = fieldAt( sq + gun[ c ] ) * amp;
		vec2 unit  = vec2( b.x / aspect, b.y );

		//Geometry error and purity error read the SAME field through two
		//different sensitivities, which is the physical arrangement: how far a
		//given field bends the beam is set by the yoke and the anode voltage,
		//and how much of a colour error that bend causes is set by the mask
		//pitch and how far the gun sits from the mask. A weak magnet gives a
		//large purity error and no measurable geometry error at all, and that
		//is the commonest real fault there is -- so the two cannot be one
		//control with a fixed ratio between them.
		vec2 d = unit * Deflection;

		//The light at this point on the glass came from the beam that was
		//aimed a displacement back up the line. Overscan and the HT sag both
		//scale the raster: a set deliberately scans wider than its own tube so
		//the blanking edges hide behind the bezel, and a coil pulling the HT
		//down slows the electrons, which makes the same yoke current bend them
		//further. The picture visibly swells while it degausses.
		vec2 src = ( pic - d ) / max( Overscan * ( 1.0 + Swell ), 0.05 );
		vec2 st  = src * 0.5 + 0.5;

		//Clamp in PICTURE space, then scale by MaxUV at the fetch. The host's
		//texture can be larger than the picture drawn into it, and a warp that
		//samples a scaled coordinate walks into that undrawn padding.
		vec2 fetch = clamp( st, halfTexel, 1.0 - halfTexel ) * MaxUV;
		vec4 texel = texture( InputTexture, fetch );

		sampled[ c ] = texel[ c ];

		//How far off its own stripe this gun landed, in phosphor widths. The
		//vertical term is zero for a mask with no vertical structure -- an
		//aperture grille's stripes run the full height of the tube, so a
		//vertical landing error moves the beam along its own stripe and costs
		//nothing. PurityGainY carries that, and it is why a Trinitron survives
		//a magnet that stains a shadow-mask set.
		landing[ c ] = unit.x * PurityGainX + unit.y * PurityGainY;

		if( c == 1 )
		{
			//Alpha and the edge test come from the centre gun. There is no
			//picture outside the raster, and stretching the edge texel across
			//the gap reads as a smear rather than as an overscanned set.
			alpha = texel.a;

			vec2 over = max( vec2( 0.0 ) - st, st - vec2( 1.0 ) );
			inside    = 1.0 - clamp( max( over.x, over.y ) * 40.0, 0.0, 1.0 );
		}
	}

	//----------------------------------------------------------------------
	// Purity: which phosphor each gun actually hit.
	//
	// A gun is aimed at its own stripe. Displaced by one whole phosphor width
	// it lands squarely on its neighbour's, and the picture's colours rotate:
	// this is why a magnetised corner goes green rather than merely dim. In
	// between it lands across two, and the two share the light in proportion.
	//
	// The tent is exactly one phosphor wide, which makes this the identity
	// matrix at zero field. Any wider and the plugin would desaturate the
	// picture while claiming to do nothing, which is the sort of thing nobody
	// notices until it is in a show.
	//----------------------------------------------------------------------
	vec3 color = vec3( 0.0 );
	for( int c = 0; c < 3; ++c )
	{
		for( int k = 0; k < 3; ++k )
		{
			float d = float( c ) + landing[ c ] - float( k );
			d -= 3.0 * round( d / 3.0 );//the stripes repeat every triad
			color[ k ] += sampled[ c ] * max( 0.0, 1.0 - abs( d ) );
		}
	}

	//A coil that big pulls the HT down and the whole picture with it.
	color *= 1.0 - Sag * 0.55;

	color *= inside;
	alpha *= inside;

	fragColor = vec4( color, alpha );
}
`;
export const PHOSPHOR = `#version 410 core
uniform sampler2D CurrentTexture;
uniform sampler2D HistoryTexture;
uniform vec3 Decay;

in vec2 uv;

out vec4 fragColor;

void main()
{
	//Both textures are ours, so both are exactly the size of the picture and
	//neither needs MaxUV.
	vec4 current = texture( CurrentTexture, uv );
	vec4 history = texture( HistoryTexture, uv );

	//Emission adds; it does not blend. A phosphor that is still glowing from
	//the last frame does not stop the new beam lighting it further, and a mix()
	//here would dim every moving highlight instead of trailing it.
	vec3 glow = max( current.rgb, history.rgb * Decay );

	fragColor = vec4( glow, max( current.a, history.a * Decay.g ) );
}
`;
export const BLOOM = `#version 410 core
uniform sampler2D SourceTexture;
uniform vec2 SourceSize;
uniform float Threshold;

in vec2 uv;

out vec4 fragColor;

void main()
{
	vec3 c = texture( SourceTexture, uv ).rgb;

	//Only what is bright enough to scatter visibly. Subtracting the threshold
	//rather than testing against it keeps the halo continuous as a highlight
	//fades, instead of switching on the frame it crosses the line.
	vec3 bright = max( c - vec3( Threshold ), vec3( 0.0 ) );

	fragColor = vec4( bright, 1.0 );
}
`;
export const BLUR = `#version 410 core
uniform sampler2D SourceTexture;
uniform vec2 Direction;

in vec2 uv;

out vec4 fragColor;

void main()
{
	const float offsets[ 3 ] = float[ 3 ]( 0.0, 1.3846153846, 3.2307692308 );
	const float weights[ 3 ] = float[ 3 ]( 0.2270270270, 0.3162162162, 0.0702702703 );

	vec3 sum = texture( SourceTexture, uv ).rgb * weights[ 0 ];
	for( int i = 1; i < 3; ++i )
	{
		vec2 d = Direction * offsets[ i ];
		sum += texture( SourceTexture, uv + d ).rgb * weights[ i ];
		sum += texture( SourceTexture, uv - d ).rgb * weights[ i ];
	}

	fragColor = vec4( sum, 1.0 );
}
`;
export const SCREEN = `#version 410 core
uniform sampler2D ScreenTexture;
uniform sampler2D BloomTexture;
uniform vec2 OutputSize;

uniform float TubeEnabled;

uniform float MaskPattern;
uniform float MaskPitch;//output pixels per phosphor stripe
uniform float MaskStrength;
uniform float MaskSpill;
uniform float MaskGain;

uniform float Scanlines;
uniform float LineCount;
uniform float BeamBloom;
uniform float Halation;
uniform float Brightness;
uniform float Contrast;

uniform float Curvature;
uniform float CornerRadius;
uniform float PerspectiveX;
uniform float PerspectiveY;
uniform float Zoom;
uniform float Vignette;

in vec2 uv;

out vec4 fragColor;

const float FOCAL = 2.4;

mat3 rotationX( float a )
{
	float s = sin( a ), c = cos( a );
	return mat3( 1.0, 0.0, 0.0,
	             0.0, c, s,
	             0.0, -s, c );
}

mat3 rotationY( float a )
{
	float s = sin( a ), c = cos( a );
	return mat3( c, 0.0, -s,
	             0.0, 1.0, 0.0,
	             s, 0.0, c );
}

//---------------------------------------------------------------------------
// The phosphor layout, as the transmission of each of the three phosphors at
// this point. Coordinates are in phosphor widths, so one unit is one stripe in
// both axes whatever the pitch is set to -- which is the same unit the beam
// pass measured its landing error in, and they have to agree or the purity
// stain will not line up with the mask that is supposed to be causing it.
//---------------------------------------------------------------------------
vec3 dotMask( vec2 mc, int pattern )
{
	if( pattern == 1 )
	{
		//Delta shadow mask: round dots on a hexagonal lattice, every other row
		//offset by half a triad. The consumer television mask.
		const float rowHeight = 0.866;//sqrt(3)/2 -- what makes the lattice regular
		float row  = floor( mc.y / rowHeight );
		float x    = mc.x + mod( row, 2.0 ) * 0.5;
		float idx  = mod( floor( x ), 3.0 );
		vec2 cell  = vec2( fract( x ) - 0.5, ( fract( mc.y / rowHeight ) - 0.5 ) * rowHeight );
		float spot = 1.0 - smoothstep( 0.24, 0.46, length( cell ) );
		vec3 phos  = idx < 0.5 ? vec3( 1.0, 0.0, 0.0 ) : ( idx < 1.5 ? vec3( 0.0, 1.0, 0.0 ) : vec3( 0.0, 0.0, 1.0 ) );
		return phos * spot;
	}

	if( pattern == 2 )
	{
		//Aperture grille: continuous vertical stripes held apart by tensioned
		//wires. No vertical structure at all -- which is exactly why the beam
		//pass leaves MaskStaggers at zero for this one, and why a Trinitron
		//shrugs off a vertical purity error that would stain a shadow mask.
		float idx    = mod( floor( mc.x ), 3.0 );
		float stripe = 1.0 - smoothstep( 0.26, 0.50, abs( fract( mc.x ) - 0.5 ) );
		vec3 phos    = idx < 0.5 ? vec3( 1.0, 0.0, 0.0 ) : ( idx < 1.5 ? vec3( 0.0, 1.0, 0.0 ) : vec3( 0.0, 0.0, 1.0 ) );
		return phos * stripe;
	}

	if( pattern == 3 )
	{
		//Slot mask: stripes broken into slots so the sheet keeps its rigidity,
		//alternate triads staggered vertically. What most later sets used.
		const float slotHeight = 2.0;
		float idx     = mod( floor( mc.x ), 3.0 );
		float stagger = mod( floor( mc.x / 3.0 ), 2.0 ) * 0.5;
		float sy      = fract( mc.y / slotHeight + stagger );
		float stripe  = 1.0 - smoothstep( 0.28, 0.50, abs( fract( mc.x ) - 0.5 ) );
		float slot    = 1.0 - smoothstep( 0.38, 0.50, abs( sy - 0.5 ) );
		vec3 phos     = idx < 0.5 ? vec3( 1.0, 0.0, 0.0 ) : ( idx < 1.5 ? vec3( 0.0, 1.0, 0.0 ) : vec3( 0.0, 0.0, 1.0 ) );
		return phos * stripe * slot;
	}

	if( pattern == 4 )
	{
		//Hard RGB stripe: no gap, no vertical structure. Not a mask any tube
		//ever had, but it is what a coarse subpixel grid looks like and it
		//stays legible at pitches where the others have turned to mush.
		float idx = mod( floor( mc.x ), 3.0 );
		return idx < 0.5 ? vec3( 1.0, 0.0, 0.0 ) : ( idx < 1.5 ? vec3( 0.0, 1.0, 0.0 ) : vec3( 0.0, 0.0, 1.0 ) );
	}

	return vec3( 1.0 );
}

void main()
{
	//----------------------------------------------------------------------
	// Interference Only: hand back what the beam and the phosphor produced.
	//----------------------------------------------------------------------
	if( TubeEnabled < 0.5 )
	{
		fragColor = texture( ScreenTexture, uv );
		return;
	}

	float aspect = OutputSize.x / max( OutputSize.y, 1.0 );

	//----------------------------------------------------------------------
	// 1. Undo the view: which point on the tube's face is this output pixel
	//    looking at? Everything after this is in the tube's own coordinates.
	//----------------------------------------------------------------------
	vec2 p = uv * 2.0 - 1.0;
	p.x *= aspect;//square units, so a rotation is a rotation

	mat3 orientation = rotationY( PerspectiveX ) * rotationX( PerspectiveY );
	vec3 dir     = vec3( p / max( Zoom, 0.05 ), FOCAL );
	vec3 normal  = orientation * vec3( 0.0, 0.0, 1.0 );
	vec3 centre  = vec3( 0.0, 0.0, FOCAL );

	//Guarded rather than branched: an early return here would leave the
	//derivatives below undefined for the whole quad, and both the scanline and
	//the mask anti-aliasing depend on them.
	float denom = dot( normal, dir );
	denom = denom >= 0.0 ? max( denom, 1e-4 ) : min( denom, -1e-4 );
	float t = dot( normal, centre ) / denom;

	vec3 local    = transpose( orientation ) * ( t * dir - centre );
	vec2 tube     = vec2( local.x / aspect, local.y );
	float infront = step( 1e-4, t );//the face is behind the eye at absurd angles

	//----------------------------------------------------------------------
	// 2. Undo the curvature, divided through by the expansion at the corner.
	//    Without that the distortion pulls the picture's own corners inside
	//    the glass and shows black beyond them, which is the one thing a
	//    correctly set-up television never does.
	//----------------------------------------------------------------------
	float cornerExpansion = 1.0 + Curvature;
	vec2 curved   = tube * ( 1.0 + Curvature * 0.5 * dot( tube, tube ) ) / cornerExpansion;
	vec2 screenUV = curved * 0.5 + 0.5;

	//----------------------------------------------------------------------
	// 3. Scan. The beam is a spot with a profile, not a row of squares, and it
	//    is fatter where it is brighter because more current defocuses it.
	//
	//    There is no authentic raster to take the line count from -- this
	//    plugin runs at the composition's resolution and models a magnet, not
	//    a broadcast standard -- so the operator says how many lines the set
	//    had, and the sampling follows from that.
	//----------------------------------------------------------------------
	float lines = max( LineCount, 1.0 );
	float lineF = screenUV.y * lines - 0.5;//integer at line centres
	float base  = floor( lineF );

	//Below roughly a pixel and a bit per line there is nothing left to draw
	//and the modulation is pure aliasing, so it fades out.
	float pixelsPerLine = 1.0 / max( fwidth( lineF ), 1e-5 );
	float scanAA = smoothstep( 1.2, 2.0, pixelsPerLine );

	vec3 beamSum   = vec3( 0.0 );
	float alphaSum = 0.0;
	float weightSum = 0.0;
	float weightFlat = 0.0;

	for( int i = -1; i <= 1; ++i )
	{
		float li = base + float( i );
		vec4 c   = texture( ScreenTexture, vec2( screenUV.x, ( li + 0.5 ) / lines ) );

		//A brighter line is a fatter line: more beam current means a bigger
		//spot, which is why highlights on a CRT swell into the gaps between
		//scan lines and shadows do not.
		float luma  = clamp( dot( abs( c.rgb ), vec3( 0.299, 0.587, 0.114 ) ), 0.0, 1.0 );
		float sigma = mix( 0.26, mix( 0.34, 0.95, BeamBloom ), luma );

		float d = lineF - li;
		float w = exp( -0.5 * d * d / ( sigma * sigma ) );
		//The same profile sampled dead-on: what the line would be worth if the
		//beam were centred here. Their ratio is the scan modulation and is
		//independent of the picture, so strength 0 returns the picture intact.
		float wFlat = exp( -0.5 * float( i ) * float( i ) / ( sigma * sigma ) );

		beamSum    += c.rgb * w;
		alphaSum   += c.a * w;
		weightSum  += w;
		weightFlat += wFlat;
	}

	vec3 color    = beamSum / max( weightSum, 1e-4 );
	float alpha   = alphaSum / max( weightSum, 1e-4 );
	float scanMod = weightSum / max( weightFlat, 1e-4 );
	color *= mix( 1.0, min( scanMod, 1.0 ), Scanlines * scanAA );

	//----------------------------------------------------------------------
	// Halation, then the picture controls, in that order: the front panel
	// adjusts the beam, and the glass scatters whatever the beam produced.
	//----------------------------------------------------------------------
	color += texture( BloomTexture, screenUV ).rgb * Halation;
	color = ( color - 0.5 * alpha ) * Contrast + 0.5 * alpha;
	color *= Brightness;

	//----------------------------------------------------------------------
	// 4. Mask, in tube coordinates.
	//----------------------------------------------------------------------
	int pattern = int( MaskPattern + 0.5 );
	vec2 maskCoord = ( tube * 0.5 + 0.5 ) * OutputSize / max( MaskPitch, 1.0 );

	//Once a phosphor is smaller than a pixel the mask is no longer a mask, it
	//is a moire generator. Fade it on the derivative rather than on a
	//resolution check, so it also does the right thing when perspective
	//shrinks the tube. The worst axis, not the length of the pair: the two are
	//independent and combining them would overstate the rate by root two.
	vec2 maskRate = fwidth( maskCoord );
	float maskAA = 1.0 - smoothstep( 0.4, 0.8, max( maskRate.x, maskRate.y ) );

	//The spot is wider than one phosphor, so its neighbours are always partly
	//lit. That floor is why a real mask reads as a texture over the picture
	//rather than as three separated primaries.
	vec3 shape     = mix( vec3( MaskSpill ), vec3( 1.0 ), dotMask( maskCoord, pattern ) );
	float strength = MaskStrength * maskAA;
	color *= mix( vec3( 1.0 ), shape * MaskGain, strength );

	//Damper wires. Only on a grille -- a perforated sheet holds itself up.
	//They are the giveaway that you are looking at a Trinitron.
	if( pattern == 2 )
	{
		float wire = 0.0;
		wire += 1.0 - smoothstep( 0.0, 3.2 / OutputSize.y, abs( tube.y - 0.36 ) );
		wire += 1.0 - smoothstep( 0.0, 3.2 / OutputSize.y, abs( tube.y + 0.36 ) );
		color *= 1.0 - clamp( wire, 0.0, 1.0 ) * 0.28 * strength;
	}

	//----------------------------------------------------------------------
	// The edge of the glass.
	//----------------------------------------------------------------------
	color *= 1.0 - Vignette * smoothstep( 0.25, 1.5, length( tube * vec2( 0.92, 1.0 ) ) );

	//A rounded rectangle in the tube's own coordinates, so the bezel keeps its
	//shape when the set is turned away from you.
	float radius = max( CornerRadius, 0.001 );
	vec2 q  = abs( tube ) - vec2( 1.0 - radius );
	float sd = length( max( q, vec2( 0.0 ) ) ) + min( max( q.x, q.y ), 0.0 ) - radius;
	float aa = max( fwidth( sd ), 1e-4 );
	float face = 1.0 - smoothstep( -aa, aa, sd );

	//Curvature can push the sample outside the raster before the face mask
	//cuts it off; there is no picture out there.
	vec2 outside = step( vec2( 0.0 ), -screenUV ) + step( vec2( 1.0 ), screenUV );
	face *= ( 1.0 - clamp( outside.x + outside.y, 0.0, 1.0 ) ) * infront;

	//Coverage, so both together.
	fragColor = vec4( clamp( color, vec3( 0.0 ), vec3( 1.0 ) ) * face, clamp( alpha, 0.0, 1.0 ) * face );
}
`;
